name: easy_dialog
description: Easy Dialog package helps you easily create basic or custom dialogs.
version: 1.0.4
authors: 
- Ricardo Niño <ricardonior@gmail.com>
- Javier Duarte <javierandresduarte@gmail.com>

homepage: https://github.com/ricardonior29/easy_dialog

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


